- name: create directory for keys
  become: yes
  become_method: sudo
  file: path=/etc/ssl/local state=directory

- name: copying letsencrypt keys if they exist
  become: yes
  become_method: sudo
  copy: src="~/.tuxlab/{{ item }}" dest=/etc/ssl/local/{{ item }}
  when: ssl_key.stat.exists
  with_items:
    - host.key
    - host.key.pub

- name: copying static keys if letsencrypt keys not found
  become: yes
  become_method: sudo
  copy: src="local/{{ item }}" dest=/etc/ssl/local/{{ item }}
  when: not ssl_key.stat.exists
  with_items:
    - host.key
    - host.key.pub

- name: copy tls keys to meteor
  become: yes
  become_method: sudo
  shell: echo '{{ item.stdout }}' >> /etc/ssl/local/{{ item.item }}
  when: ('security_group_meteor' in group_names or 'tuxlab-meteor' in group_names)
  with_items: "{{ hostvars['dswarm']['swarm_certs'].results }}"
  no_log: yes
