---
- name: update packages
  become: yes
  become_method: sudo
  yum: name=* state=latest

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  become: yes
  become_method: sudo
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Import EPEL GPG key.
  become: yes
  become_method: sudo
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Flush Network Interface
  become: yes
  become_method: sudo
  shell: |
    service NetworkManager stop
    service network restart
    chkconfig network on

- name: Install git
  sudo: true
  yum: name=git state=latest

- name: Install etcd
  sudo: true
  yum: name=etcd state=latest
