---
- name: update packages
  become: yes
  yum: name=* state=latest

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  become: yes
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Import EPEL GPG key.
  become: yes
  become_method: sudo
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Reload Network Services
  become: yes
  systemd:
    name: network
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Chkconfig Network
  become: yes
  shell: chkconfig network on

- name: Install git
  become: yes
  yum: name=git state=latest

- name: Install etcd
  become: yes
  yum: name=etcd state=latest
