---
###############################
#    DOMAIN CONFIGURATION     #
###############################
   TUX_DOMAIN: cmu.tuxlab.org
   TUX_HOMEPAGE: http://cmu.tuxlab.org/
   TUX_EMAIL: service@tuxlab.org

###############################
#      APP CONFIGURATION      #
###############################
   APP_REPO_GIT: https://github.com/learnlinux/tuxlab-app
   #APP_REPO_BIN: https://api.github.com/repos/learnlinux/tuxlab/tarball/v1.0.0

###############################
#    LABENV CONFIGURATION     #
###############################
   LAB_IMAGES: [{ url: "https://github.com/learnlinux/tuxlab-labvm-alpine.git", directory: /home/core/tuxlab-labvm-alpine, image_name: tuxlab_labvm_alpine }]

###############################
#    MONGODB CONFIGURATION    #
###############################

   MONGO_ROOT: ds025792.mlab.com:25792
   MONGO_URL: ds025792.mlab.com:25792/tuxlab
   MONGO_USER: tuxlab
   MONGO_PASS: [REDACTED]
   MONGO_EMAIL: smtp://smtp.tuxlab.org/

###############################
#      AWS CONFIGURATION      #
###############################
   EC2_REGION: us-east-1
   EC2_AZ: us-east-1a

  # Ansible Tower
   TOWER_IMAGE: ami-a013f9cd
   TOWER_INSTANCE_TYPE: m3.medium

  # Docker Swarm Manager Settings
   SWARM_IMAGE: ami-8d6485e0
   SWARM_INSTANCE_TYPE: t2.medium

  # Docker Host Settings
   DOCKER_IMAGE: ami-8d6485e0
   DOCKER_INSTANCE_TYPE: t2.medium
   DOCKER_MAX_INSTANCES: 1

  # Meteor Server Settings
   METEOR_IMAGE: ami-6d1c2007
   METEOR_INSTANCE_TYPE: t2.medium
   METEOR_MAX_INSTANCES: 1
