---
###############################
#    DOMAIN CONFIGURATION     #
###############################
   TUX_DOMAIN: tuxlab.local
   TUX_ORG: Carnegie Mellon University
   TUX_HOMEPAGE: http://tuxlab.local/
   TUX_EMAIL: service@tuxlab.org

###############################
#     SSL CONFIGURATION       #
###############################
   SSL_COUNTRY: US
   SSL_STATE: Pennsylvania
   SSL_LOCALITY: Pittsburgh
   SSL_ORG: "{{ TUX_ORG }}"
   SSL_ORG_UNIT: TuxLab

###############################
#    LABENV CONFIGURATION     #
###############################
   LAB_IMAGES:
    - 'tuxlab/labvm-alpine'

###############################
#      AUTH CONFIGURATION     #
###############################

  # SETUP ON GOOGLE
  # Authorized Origins: http://cmu.tuxlab.org
  # Redirect URL: http://cmu.tuxlab.org/_oauth/google?close
   AUTH_GOOGLE: true
   AUTH_GOOGLE_CLIENTID: 445449178719-bo39meu0kin7akfi46nl0e1e1540lc2u.apps.googleusercontent.com
   AUTH_GOOGLE_SECRET: AXGTICuk0E71DnyT5gFtgrYD
   AUTH_GOOGLE_DOMAIN: "@andrew.cmu.edu"
