---
###############################
#    DOMAIN CONFIGURATION     #
###############################
   TUX_DOMAIN: tuxlab.local
   TUX_ORG: Carnegie Mellon University
   TUX_HOMEPAGE: http://tuxlab.local/
   TUX_EMAIL: service@tuxlab.org
   TUX_EMAIL_URL: smtp://mail.tuxlab.local

###############################
#     SSL CONFIGURATION       #
###############################
   SSL_COUNTRY: US
   SSL_STATE: Pennsylvania
   SSL_LOCALITY: Pittsburgh
   SSL_ORG: "{{ TUX_ORG }}"
   SSL_ORG_UNIT: TuxLab

###############################
#    LABENV CONFIGURATION     #
###############################
   LAB_IMAGES:
    - 'tuxlab/labvm-alpine'
