---
  # This Playbook automatically deploys the TuxLab Application to AWS
  # by creating an Ansible Tower node. Be sure to set aws variables in
  # ./vars/aws_vars.yml file prior to execution.

  # Create AWS Enviornment
  - name: Create EC2 Enviornment
    hosts: localhost
    connection: local
    remote_user: root
    gather_facts: no
    tasks:
      - name: Create AWS VPC
        include: aws/ec2_vpc.yml

      - name: Create AWS Keypair
        include: aws/ec2_key.yml

      - name: Create AWS Tower
        include: aws/ec2_tower.yml

      - name: Create Security Groups
        include: aws/ec2_groups.yml

      - name: Create Docker EC2 Enviornment
        include: aws/ec2_docker.yml

      - name: Create Meteor EC2 Enviornment
        include: aws/ec2_meteor.yml

      - name: Configure AWS Tower Playbooks
        include: aws/ec2_tower_config.yml
