---

## DOWNLOAD
  - name: remove current build
    become: yes
    become_method: sudo
    file: path={{ deploy_dir }} state=absent

  - name: Create {{ deploy_dir }}
    become: yes
    become_method: sudo
    file: name={{ item }} state=directory owner=root group=root recurse=yes
    with_items:
      - "{{ deploy_dir }}"
      - "{{ deploy_app_dir }}"
    when: binary_deploy

  - name: download binary
    get_url: url={{ repo_url }} dest={{deploy_dir}}/tuxlab-app.tar.gz
    when: binary_deploy

  - name: unzip binary
    unarchive: src={{deploy_dir}}/tuxlab-app.tar.gz dest={{deploy_app_dir}}
    when: binary_deploy

  - name: clone tuxlab source
    git: repo={{repo_url}}
         dest={{deploy_dir}}
         accept_hostkey=yes
    when: not binary_deploy

  - name: grant ansible user ownership
    file: path={{deploy_dir}} owner={{ansible_user}} recurse=yes
    become: yes
    become_method: sudo

## INSTALL
  - name: install npm dependencies
    npm: path={{deploy_dir}} production=yes
    when: not binary_deploy

  - name: install typings
    become: yes
    become_method: sudo
    npm: name=typings global=yes

  - name: typings install
    shell: typings install chdir={{deploy_dir}}

## COPY SETTINGS
  - name: Copy settings.env.json
    template: src="settings.env.json.j2"
              dest="{{deploy_dir}}/private/settings.env.json"
              mode=0644

## BUILD AND RUN
  - name: build tuxlab app
    become: yes
    become_method: sudo
    shell: /usr/local/bin/meteor build --directory {{deploy_app_dir}} chdir={{deploy_dir}}
    when: not binary_deploy

  - name: install forvever
    npm: name=forever global=yes state=present

  - name: set mongodb URL
    become: yes
    become_method: sudo
    shell: MONGO_URL={{ mongo_url }}
    when: "'security_group_meteor' in group_names"

  - name: start tuxlab app
    become: yes
    become_method: sudo
    shell:  >
      PORT=80
      ROOT_URL={{ root_url }}
      MAIL_URL={{ mail_url }}
      forever start "{{ deploy_app_dir }}"bundle/main.js
    async: 10
    poll: 1
