---
  - name: remove current build
    become: yes
    become_method: sudo
    file: path={{ deploy_dir }} state=absent

  - name: Create {{ deploy_dir }}
    become: yes
    become_method: sudo
    file: name={{ item }} state=directory owner=root group=root recurse=yes
    with_items:
      - "{{ deploy_dir }}"
      - "{{ deploy_app_dir }}"
    when: binary_deploy

  - name: download binary
    get_url: url={{ repo_url }} dest={{deploy_dir}}/tuxlab-app.tar.gz
    when: binary_deploy

  - name: unzip binary
    unarchive: src={{deploy_dir}}/tuxlab-app.tar.gz dest={{deploy_app_dir}}
    when: binary_deploy

  - name: clone tuxlab source
    become: yes
    become_method: sudo
    git: repo={{repo_url}}
         dest={{deploy_dir}}
         accept_hostkey=yes
    when: not binary_deploy

  - name: install npm dependencies
    become: yes
    become_method: sudo
    npm: path={{deploy_dir}} production=yes
    when: not binary_deploy

  - name: typings install
    become: yes
    become_method: sudo
    shell: typings install chdir={{deploy_dir}}

  - name: build tuxlab app
    become: yes
    become_method: sudo
    shell: /usr/local/bin/meteor build --directory {{deploy_app_dir}} chdir={{deploy_dir}}
    when: not binary_deploy

  - name: install forvever
    npm: name=forever global=yes state=present

  - name: start tuxlab app
    become: yes
    become_method: sudo
    shell:  >
      PORT=80
      MONGO_URL={{ mongo_url }}
      ROOT_URL={{ root_url }}
      forever start "{{ deploy_app_dir }}"/main.js
    async: 10
    poll: 1
