---

## VERSION 1.4 FIXES
  - name: remove current meteor installation
    become: yes
    file: path=~./meteor state=absent

  - name: remove meteor local files
    become: yes
    file: path=/var/tuxlab/meteor/local state=absent

  - name: remove meteor dev bundle
    become: yes
    file: path=/var/tuxlab/meteor/dev_bundle state=absent

  - name: modify tuxlab ownership
    become: yes
    file: path=/var/tuxlab state=directory owner={{ ansible_user }}

## RUN SETUP
  - name: Production Setup
    include: "production.yml"
    when: deployment_method == "production" | default(true)

  - name: Testing Setup
    include: "testing.yml"
    when: deployment_method == "testing" | default(false)

  - name: Vagrant Setup
    include: "vagrant.yml"
    when:  deployment_method == "vagrant" | default(false)
