## COPY FILES
  - name: remove existing files
    become: yes
    file: path={{ item }} state=absent
    with_items:
      - "{{ source_dir }}"
      - "{{ deploy_dir }}"

  - name: create directories
    become: yes
    file: name={{ item }} state=directory owner={{ ansible_user }}
    with_items:
      - "{{ source_dir }}"
      - "{{ source_dir }}/private"
      - "{{ deploy_dir }}"

  - name: pull tuxlab-app
    synchronize:
      src: "{{ local_dir }}"
      dest: "{{ source_dir }}"
      verify_host: no

## COPY SETTINGS
  - name: Copy settings
    template:
      src: "settings.json.j2"
      dest: "{{source_dir}}/private/settings.json"
      force: yes
      mode: 0644

## RUN
  - name: npm install
    shell: "/usr/local/bin/meteor npm install"
    args:
      chdir: "{{source_dir}}"

## COPY SERVICE
  - name: Copy Service
    become: yes
    template:
      src: "tuxlab-test.service.j2"
      dest: "/etc/systemd/system/tuxlab-test.service"
      mode: 0644

  - name: Daemon Reload
    become: yes
    shell: systemctl daemon-reload

## START SERVICE
  - name: Start TuxLab Service
    become: yes
    service:
       name: tuxlab-test
       state: started
       enabled: yes
## REDIRECT
  - name: Forward Ports
    become: yes
    shell: "iptables -A PREROUTING -t nat -i {{ etcd_interface }} -p tcp --dport 80 -j REDIRECT --to-port 3000"
