## COPY SETTINGS

  - name: Create directory
    become: yes
    file:
      state: directory
      path: "{{vagrant_dir}}/private/"
      mode: 0755
      owner: vagrant

  - name: Copy settings
    become: yes
    template:
      src: "settings.json.j2"
      dest: "{{vagrant_dir}}/private/settings.json"
      force: yes
      mode: 0755
