---
- name: start swarm-manager
  become: yes
  become_method: sudo
  shell: docker run -d --expose 4000 -e SWARM_HOST=":4000" --restart on-failure --name swarm-manager --net=host  -v /home/core/.docker:/certs:ro swarm:latest manage --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/cert.pem --tlskey=/certs/key.pem etcd://127.0.0.1:2379/swarm
