---
- name: start swarm-manager
  become: yes
  become_method: sudo
  shell: >
    docker run -d --expose 4000 -e SWARM_HOST=":4000"
    --restart on-failure --name swarm-manager
    --net=host  swarm:latest manage
    --discovery-opt kv.cacertfile=/etc/ssl/local/ca.pem
    --discovery-opt kv.certfile=/etc/ssl/local/cert.pem
    --discovery-opt kv.keyfile=/etc/ssl/local/host.pem
    etcd://127.0.0.1:2379/swarm
