---

- name: copy session daemon settings
  become: yes
  template: src=settings.json.j2 dest=/root/tuxlab-sessiond-settings.json

#TODO: https://github.com/ansible/ansible-modules-core/issues/5515
- name: pull session-daemon image
  become: yes
  shell: docker pull tuxlab/session-daemon

- name: run session-daemon container
  become: yes
  docker_container:
    name: session-daemon
    image: tuxlab/session-daemon
    state: started
    restart_policy: on-failure
    volumes:
      - ~/tuxlab-sessiond-settings.json:/settings.json:ro
      - /etc/ssl/local:/ssl:ro
