---

- name: pull alpine container images with sshd
  become: yes
  become_method: sudo
  git: repo=https://github.com/learnlinux/docker-sshd.git dest=docker-sshd

- name: build tuxlab_sshd image
  docker_image:
    path: ~/docker-sshd
    name: tuxlab_sshd
