---

#- name: install pexpect
#  become: yes
#  become_method: sudo
#  pip: name=pexpect version=3.3
#  delegate_to: localhost
#  run_once: true

- name: register home directory
  local_action: command echo $HOME
  register: home_dir

- name: generate ca-key.pem
  expect:
    command: openssl genrsa -aes256 -out {{ home_dir.stdout }}/.tuxlab/ca-key.pem 4096
    responses:
      pass: "guest"
  delegate_to: localhost
  run_once: true

- name: generate ca.pem
  become: yes
  become_method: sudo
  expect:
    command: openssl req -new -x509 -days 365 -key {{ home_dir.stdout }}/.tuxlab/ca-key.pem -sha256 -out {{ home_dir.stdout }}/.tuxlab/ca.pem
    responses:
      pass: "guest"
      Country: "US"
      State: "Pennsylvania"
      Locality: "Pittsburgh"
      company: "TuxLab"
      section: "."
      FQDN: "."
      Email: "."
  delegate_to: localhost
  run_once: true

- name: register ca contents
  become: yes
  become_method: sudo
  set_fact: ca_content="{{ lookup('file', '{{ home_dir.stdout }}/.tuxlab/ca.pem') }}"
  delegate_to: localhost

- name: register ca key contents
  become: yes
  become_method: sudo
  set_fact: ca_key_content="{{ lookup('file', '{{ home_dir.stdout }}/.tuxlab/ca-key.pem') }}"
  delegate_to: localhost
