---

  # Install SkyDNS
- name: pull dns repo
  git: repo=https://github.com/learnlinux/tuxlab-dns.git
       dest=~/skydns

- name: build tuxlab_dns image from binary
  shell: "docker build -t tuxlab_dns ~/skydns"

# Configure Options
- name: create skydns etcd directory
  shell: "etcdctl -u root:{{ root_pass }} mkdir skydns"

- name: create skydns config directory
  shell: "etcdctl -u root:{{ root_pass }} mkdir skydns/config"

- name: set authoritative domain
  shell: "etcdctl -u root:{{ root_pass }} put skydns/config/domain {{ TUX_DOMAIN }}"

- name: set hostmaster
  shell: "etcdctl -u root:{{ root_pass }} put skydns/config/domain {{ TUX_EMAIL }}"

# Start DNS Container
- name: start dns container
  shell: >
    docker run -d
    --name swarm-dns
    --restart on-failure
    --expose 53
    --net=host
    -e ETCD_MACHINES='http://172.17.0.1:2379'
    -e ETCD_USERNAME='{{ }}'
    -e ETCD_PASSWORD='{{}}'
    tuxlab_dns
