---

# Configure Options
- name: create skydns config
  shell: "etcdctl -u dns:{{ dns_pass }} set skydns/config '{\"domain\" : \"{{TUX_DOMAIN}}\", \"hostmaster\" : \"{{ TUX_EMAIL }}\"}'"

- name: start dns container
  become: yes
  become_method: sudo
  shell: >
        docker run -d
        --name swarm-dns
        --restart on-failure
        --expose 53
        --net=host
        -tls-key='/etc/ssl/local/host.pem'
        -tls-pem='/etc/ssl/local/cert.pem'
        -ca-cert='/etc/ssl/local/ca.pem'
        skynetservices/skydns:latest
