---

- name: pull dns repo
  git: repo=https://github.com/learnlinux/helixdns.git
       dest=~/helixdns

- name: build tuxlab_dns image from binary
  become: yes
  become_method: sudo
  shell: "docker build -t tuxlab_dns /home/core/helixdns/docker"

- name: start dns container
  become: yes
  become_method: sudo
  shell: "docker run -d --name swarm-dns --restart on-failure --expose 53 --net=host tuxlab_dns ./hdns"

- name: create helix etcd directory
  shell: "etcdctl -u root:{{ root_pass }} mkdir helix"
