---

# Configure Options
- name: create skydns config
  shell: "etcdctl -u dns:{{ dns_pass }} set skydns/config '{\"domain\" : \"{{TUX_DOMAIN}}\", \"hostmaster\" : \"{{ TUX_EMAIL }}\"}'"

- name: start dns container
  become: yes
  become_method: sudo
  shell: >
        docker run -d
        --name swarm-dns
        --restart on-failure
        --expose 53
        --net=host
        -e ETCD_MACHINES='http://172.17.0.1:2379'
        -e ETCD_USERNAME='dns'
        -e ETCD_PASSWORD='{{ dns_pass }}'
        skynetservices/skydns:latest
