---

- name: pull dns repo
  git: repo=https://github.com/learnlinux/helixdns.git
       dest=~/helixdns

- name: build tuxlab_dns image from binary
  shell: "docker build -t tuxlab_dns ~/helixdns/docker"

- name: start dns container
  shell: "docker run -d -p 53:53 --name swarm-dns tuxlab_dns ./hdns"

- name: create helix etcd directory
  shell: "etcdctl mkdir helix"
