---

- name: pull alpine container images with redbird
  git: repo=https://github.com/learnlinux/tuxlab-reverse-proxy.git dest=/home/core/tuxlab-reverse-proxy

- name: copying Settings
  become: yes
  become_method: sudo
  template: src=settings.json.j2 dest=/home/core/tuxlab-reverse-proxy/src/settings.json owner=root group=root mode=0644

- name: build tuxlab_proxy image
  become: yes
  become_method: sudo
  shell: "docker build -t tuxlab_proxy /home/core/tuxlab-reverse-proxy"

- name: start reverse proxy container
  shell: "docker run -d tuxlab_proxy"
