---
- name: copy tuxlab-proxy settings
  become: yes
  template: src=settings.json.j2 dest=/root/tuxlab-proxy-settings.json owner=root group=root mode=0644

#TODO https://github.com/ansible/ansible-modules-core/issues/5515
- name: pull ssh-proxy image
  become: yes
  shell: docker pull tuxlab/ssh-proxy

- name: start reverse proxy container
  become: yes
  docker_container:
    name: host-proxy
    image: tuxlab/ssh-proxy
    state: started
    restart_policy: on-failure
    network_mode: host
    volumes:
      - /root/tuxlab-proxy-settings.json:/settings.json:ro
      - /etc/ssl/local:/ssl:ro
