---

- name: add etcd systemd service
  become: yes
  become_method: sudo
  template: src=etc/systemd/system/etcd.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644

- name: Reload systemctl
  become: yes
  become_method: sudo
  shell: systemctl daemon-reload

- name: Enable etcd
  become: yes
  become_method: sudo
  service: name=etcd
           enabled=yes

- name: Start etcd
  become: yes
  become_method: sudo
  shell: "systemctl start etcd &"
