---

- name: stop etcd systemd service
  become: yes
  service:
    name: etcd
    state: stopped

- name: clear data directory
  become: yes
  file:
    path: "{{ etcd_data_dir }}"
    state: absent

- name: re-add data directory
  become: yes
  file:
    path: "{{ etcd_data_dir }}"
    state: directory

- name: add etcd systemd service
  become: yes
  template: src=etcd.service.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644

- name: Daemon Reload
  become: yes
  shell: systemctl daemon-reload

- name: ETCD Enable
  become: yes
  service:
    name: etcd
    state: started
    enabled: yes

- name: Save SSL Variables
  become: yes
  template:
    src: etcdctl.sh.j2
    dest: /etc/profile.d/etcdctl.sh
    mode: 0755

- name: Import SSL Variables
  become: yes
  shell: . /etc/profile.d/etcdctl.sh
