---

- name: add etcd systemd service
  sudo: true
  template: src=etc/systemd/system/etcd.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644

- name: Reload systemctl
  sudo: true
  shell: systemctl daemon-reload

- name: Enable etcd
  sudo: true
  service: name=etcd
           enabled=yes

- name: Start etcd
  sudo: true
  shell: "systemctl start etcd &"
