---

- name: stop etcd systemd service
  become: yes
  shell: systemctl stop etcd.service

- name: add etcd systemd service
  become: yes
  template: src=etcd.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644

- name: Daemon Reload
  become: yes
  shell: systemctl daemon-reload

- name: ETCD Enable
  become: yes
  shell: systemctl enable etcd.service

- name: ETCD Start
  become: yes
  shell: systemctl start etcd.service &

- name: Save SSL Variables
  become: yes
  template:
    src: etcdctl.sh.j2
    dest: /etc/profile.d/etcdctl.sh
    mode: 0755

- name: Import SSL Variables
  become: yes
  shell: . /etc/profile.d/etcdctl.sh
