---

- name: create etcd directories
  shell: "etcdctl mkdir {{ item }}"
  with_items:
    - redrouter
    - skydns

- name: Add etcd root user
  expect:
    command: etcdctl user add root
    responses:
      "New password:": "{{ root_pass }}"

- name: Enable authentication
  shell: "etcdctl auth enable"

- name: Revoke guest privileges
  shell: "etcdctl -u root:{{ root_pass }} role revoke guest -path '/*' -readwrite"

- name: Add etcd users
  expect:
    command: etcdctl -u root:{{ root_pass }} user add {{ item.user }}
    responses:
      "New password:": "{{ item.pass }}"
  with_items:
    - { user: 'dns', pass: '{{ dns_pass }}' }
    - { user: 'proxy', pass: '{{ proxy_pass }}' }
    - { user: 'meteor', pass: '{{ meteor_pass }}' }
    - { user: 'session', pass: '{{ session_pass }}' }

- name: Add etcd roles
  shell: |
    etcdctl -u root:{{ root_pass }} role add skydns;
    etcdctl -u root:{{ root_pass }} role add redrouter;
    etcdctl -u root:{{ root_pass }} role add tuxlab;
    etcdctl -u root:{{ root_pass }} role add session;

- name: Grant role permissions
  shell: |
    etcdctl -u root:{{ root_pass }} role grant skydns -path '/skydns' -readwrite;
    etcdctl -u root:{{ root_pass }} role grant skydns -path '/skydns/*' -readwrite;
    etcdctl -u root:{{ root_pass }} role grant redrouter -path '/redrouter' -readwrite;
    etcdctl -u root:{{ root_pass }} role grant redrouter -path '/redrouter/*' -readwrite;
    etcdctl -u root:{{ root_pass }} role grant tuxlab -path '/tuxlab' -readwrite;
    etcdctl -u root:{{ root_pass }} role grant tuxlab -path '/tuxlab/*' -readwrite;

- name: Grant etcd user roles
  shell: | 
    etcdctl -u root:{{ root_pass }} user grant dns -roles skydns; 
    etcdctl -u root:{{ root_pass }} user grant proxy -roles redrouter; 
    etcdctl -u root:{{ root_pass }} user grant meteor -roles skydns;
    etcdctl -u root:{{ root_pass }} user grant meteor -roles redrouter;
    etcdctl -u root:{{ root_pass }} user grant meteor -roles tuxlab;
    etcdctl -u root:{{ root_pass }} user grant session -roles tuxlab;

- name: Ensure dns user configured properly
  expect:
    command: etcdctl -u root:{{ root_pass }} user passwd dns
    responses:
      "New password:": "{{ dns_pass }}"
  register: pass_success_dns
  until: "'Password updated' in '{{ pass_success_dns.stdout }}'"
  retries: 5
  delay: 1

- name: Ensure proxy user configured properly
  expect:
    command: etcdctl -u root:{{ root_pass }} user passwd proxy
    responses:
      "New password:": "{{ proxy_pass }}"
  register: pass_success_proxy
  until: "'Password updated' in '{{ pass_success_proxy.stdout }}'"
  retries: 5
  delay: 1

- name: Ensure meteor user configured properly
  expect:
    command: etcdctl -u root:{{ root_pass }} user passwd meteor
    responses:
      "New password:": "{{ meteor_pass }}"
  register: pass_success_meteor
  until: "'Password updated' in '{{ pass_success_meteor.stdout }}'"
  retries: 5
  delay: 1

- name: Ensure session user configured properly
  expect:
    command: etcdctl -u root:{{ root_pass }} user passwd session
    responses:
      "New password:": "{{ session_pass }}"
  register: pass_success_session
  until: "'Password updated' in '{{ pass_success_session.stdout }}'"
  retries: 5
  delay: 1
