---

- name: Add etcd root user
  expect:
    command: etcdctl user add root
    responses:
      "New password:": "{{ root_pass }}"

- name: Enable authentication
  shell: "etcdctl auth enable"

- name: Revoke guest privileges
  shell: "etcdctl -u root:{{ root_pass }} role revoke guest -path '/*' -readwrite"

- name: Add etcd users
  expect:
    command: etcdctl -u root:{{ root_pass }} user add {{ item.user }}
    responses:
      "New password:": "{{ item.pass }}"
  with_items:
    - { user: 'dns', pass: '{{ dns_pass }}' }
    - { user: 'proxy', pass: '{{ proxy_pass }}' }
    - { user: 'meteor', pass: '{{ meteor_pass }}' }

- name: Add etcd roles
  shell: "etcdctl -u root:{{ root_pass }} role add skydns; etcdctl -u root:{{ root_pass }} role add redrouter;"

- name: Grant role permissions
  shell: "etcdctl -u root:{{ root_pass }} role grant skydns -path '/skydns/*' -readwrite; etcdctl -u root:{{ root_pass }} role grant redrouter -path '/redrouter/*' -readwrite"

- name: Grant etcd user roles
  shell: "etcdctl -u root:{{ root_pass }} user grant dns -roles skydns; etcdctl -u root:{{ root_pass }} user grant proxy -roles redrouter; etcdctl -u root:{{ root_pass }} user grant meteor -roles redrouter,skydns"
