---
- name: check for meteor
  shell: command -v meteor >/dev/null && echo "true" || echo "false"
  register: meteor_status

- name: install meteor
  become: yes
  shell: curl https://install.meteor.com/ | /bin/sh
  args:
    warn: false
  when: meteor_status.stdout == "false"

- name: install g++
  become: yes
  yum: name=gcc-c++ state=latest
