---
- name: restart docker
  become: yes
  become_method: sudo
  service: >
    name=docker
    state=restarted

- name: restart remote api
  become: yes
  become_method: sudo
  service: >
    name=docker-tcp.socket
    state=restrarted
