---

- name: Clone certbot repo
  run_once: true
  local_action: git repo=https://github.com/certbot/certbot.git dest=~/.tuxlab/certbot

- name: Obtain SSL Certs
  run_once: true
  local_action: shell ~/.tuxlab/certbot/letsencrypt-auto certonly -d {{ letsencrypt_domain }} --email {{ letsencrypt_email }} --standalone --cert-path ~/.tuxlab/
  ignore_errors: true

- name: Check if letsencrypt keys exist
  run_once: true
  local_action: stat path=~/.tuxlab/host.key
  ignore_errors: true
  register: ssl_key

