---

- name: copy docker conf
  sudo: true
  template: >
    src=docker-tcp-socket.j2
    dest=/etc/systemd/system/docker-tcp.socket
    owner=root
    group=root
    mode=0644

- name: enable remote api socket
  sudo: true
  service: name=docker-tcp.socket enabled=yes

- name: stop docker service
  sudo: true
  service: name=docker-tcp.socket state=stopped

- name: start remote api socket
  sudo: true
  service: name=docker-tcp.socket state=started

- name: start docker service
  sudo: true
  service: name=docker-tcp.socket state=started

- name: start swarm-agent
  shell: docker run -d --name swarm-agent --net=host swarm:latest join --addr={{ swarm_node_ip }}:2375 etcd://127.0.0.1:2379

- name: pull alpine container images with sshd
  sudo: true
  git: repo=https://github.com/learnlinux/docker-sshd.git dest=docker-sshd

- name: create tuxlab_sshd image
  shell: cd docker-sshd; docker build -t tuxlab_sshd .
