---

- name: Create .docker folder
  become: yes
  file:
      path: '/root/.docker'
      state: directory
      mode: 0755

- name: Create symlinks to docker tls keys
  become: yes
  file:
    src: '/etc/ssl/local/{{ item.src }}'
    dest: '/etc/docker/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'ca.pem', dest: 'ca.pem' }
    - { src: 'cert.pem', dest: 'cert.pem' }
    - { src: 'host.pem', dest: 'key.pem' }

- name: copy docker configuration
  become: yes
  template: >
    src=docker.j2
    dest=/etc/sysconfig/docker
    owner=root
    group=root
    mode=0644

- name: create docker group
  become: yes
  group:
    name: docker
    state: present

- name: add ansible user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: restart docker service
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: docker

- name: Save TLS Variables
  become: yes
  template:
    src: dockerctl.sh.j2
    dest: /etc/profile.d/dockerctl.sh
    mode: 0755

- name: Import TLS Variables
  become: yes
  shell: source /etc/profile.d/dockerctl.sh
