---

#TODO https://github.com/ansible/ansible-modules-core/issues/5515
- name: pull swarm image
  become: yes
  shell: docker pull swarm

- name: start swarm-manager
  become: yes
  docker_container:
    name: swarm-agent
    image: swarm
    restart_policy: on-failure
    network_mode: host
    volumes:
      - /etc/ssl/local:/certs:ro
    command: >
      join
      --addr={{ ansible_host }}:2376
      --discovery-opt kv.cacertfile=/certs/ca.pem
      --discovery-opt kv.certfile=/certs/cert.pem
      --discovery-opt kv.keyfile=/certs/host.pem
      etcd://127.0.0.1:2379/swarm
